# Generated by Django 4.1.5 on 2023-01-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
